### ISSUE TITLE
公式をWebViewに表示させる

### ISSUE THREAD

**Issue by Yuki014** [jagsc/Jagsc-Official-App#17]
## 概要

学生部の公式HPを表示できるようにする
~~初期ではホームを表示するようにして、メニューボタンをタップしたらそれぞれのページに切り替わるように変更する~~

## タスクリスト

- [x] Readyに移動する
- [x] 開発をする
- [x] レビュー　（動作確認）

**Comment by Yuki014** [comment]
Doingになってるけどどんな感じ？

**Comment by takanakahiko** [comment]
動かしまくっててウケる

**Comment by takanakahiko** [comment]
Issueを編集しました
