### ISSUE TITLE
gitignoreをgithubが提供しているものに変更する

### ISSUE THREAD

**Issue by takanakahiko** [jagsc/Jagsc-Official-App#20]
## 概要

https://github.com/github/gitignore/blob/master/Android.gitignore
上記URLのものにすり替える

## タスクリスト

- [x] Readyに移動する
- [x] 開発をする
- [x] レビュー　（動作確認）

## 備考

特にないです

**Comment by Yuki014** [comment]
そう言えばこれ、mergeしたのでcloseします
